version: '3'
services:
  example_service:
      build:
        context: ./..
        dockerfile: ./Manager-Service/Dockerfile
      ports:
        - "3200:3200"
      volumes:
        - "./config.txt:/app/config.txt"
        - "./app/log/:/app/log"
