version: '3'
services:
  active_connections_service:
      build:
        context: ./..
        dockerfile: ./Active-Connections-Service/Dockerfile
      ports:
        - "2525:2525"
        - "4551:4551"
      volumes:
        - "./config.txt:/app/config.txt"
        - "./app/log/:/app/log"
