version: '3'
services:
  example_service:
      build:
        context: ./..
        dockerfile: ./Active-Connections-Service/Dockerfile
      ports:
        - "2525:2525"
        - "4551:4551"
      volumes:
        - "./app/log/:/app/log"
