version: '3'
services:
  gate:
      build:
        context: .
        dockerfile: ./Dockerfile
      volumes:
        - "./config.txt:/app/config.txt"
        - "./../photon.conf:/app/photon.conf"
        - "./../token.base:/app/token.base"
        - "./app/log/:/app/log"
  mosquitto:
      container_name: mosquitto
      image: eclipse-mosquitto
      ports:
        - "18830:1883"
