version: '3'
services:
  alice_interface:
      build: .
      ports:
        - "4443:4443"
      command: python3 /app/index.py
      volumes:
        - "./cert.pem:/cert.pem"
        - "./key.pem:/key.pem"