CREATE DATABASE IF NOT EXISTS TestDb;
USE TestDb;

CREATE TABLE IF NOT EXISTS test_table(
	Id INT AUTO_INCREMENT NOT NULL,
	Data VARCHAR(32) NOT NULL,
	PRIMARY KEY(Id)
);

GRANT ALL ON TestDb.* TO Tester@localhost IDENTIFIED BY 'secret';
