# Generated by Django 2.2.5 on 2019-09-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gate_uid',
            name='uid',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
