
version: '3'
services:
  example_service:
      build:
        context: ./..
        dockerfile: ./Example-Service/Dockerfile
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: on-failure
    command: --init-file /data/application/init.sql
    environment:
        - MYSQL_DATABASE=django_bd
        - MYSQL_ROOT_PASSWORD=''
        - MYSQL_USER=django_user
        - MYSQL_PASSWORD=12345
    ports:
        - "33060:3306"
    volumes:
        - "./database/data/mysql:/var/lib/mysql"
        - "./database/init.sql:/data/application/init.sql"